<?php
//foreach ($this->Guestbook as $item) {
//    echo $item-> id.'==='.$item->text."</br>";
//}
?>

<!---->
<!--<style>-->
<!--    a:link,-->
<!--    a:visited-->
<!--    {-->
<!--        color: #0398CA;-->
<!--    }-->
<!---->
<!--    span#zf-name-->
<!--    {-->
<!--        color: #91BE3F;-->
<!--    }-->
<!---->
<!--    div#welcome-->
<!--    {-->
<!--        color: #FFFFFF;-->
<!--        background-image: url(http://framework.zend.com/images/bkg_header.jpg);-->
<!--        width:  600px;-->
<!--        height: 400px;-->
<!--        border: 2px solid #444444;-->
<!--        overflow: hidden;-->
<!--        text-align: center;-->
<!--    }-->
<!---->
<!--    div#more-information-->
<!--    {-->
<!--        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);-->
<!--        height: 100%;-->
<!--    }-->
<!--</style>-->
<!--<div id="welcome">-->
<!--    <h1>Welcome to the Guestbook index!!!!</h1>-->
<!---->
<!--    <h3>This is your project's main page</h3>-->
<!---->
<!--    <div id="more-information">-->
<!--        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>-->
<!--        <p>-->
<!--            Helpful Links: <br />-->
<!--            <a href="http://framework.zend.com/">Zend Framework Website</a> |-->
<!--            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>-->
<!--        </p>-->
<!--    </div>-->
<!--</div>-->




<p><a href="<?php echo $this->url(
    array(

        'controller' => 'page',
        'action'     => 'sign'
    ),
    'default',
    true) ?>">Sign Our Guestbook</a></p>

<p> Sort by date <a href="<?php echo $this->url(array('field_name' => 'created','sort' => 'DESC'), 'goods') ?>">&darr;</a>
    <a href="<?php echo $this->url(array('field_name' => 'created','sort' => 'ASC'), 'goods') ?>">&uarr;</a>

</p>

Guestbook Entries: <hr> <br />

<TABLE  width="100%">
<?php foreach ($this->entries as $entry): ?>

    <TR>

        <TD><?php echo 'username  '.$this->escape($entry->user)."<br />"."<br />".nl2br($entry->comment) ?></TD>
    </TR>

    <TR align=right>
        <TD><?php  echo 'date  '.$this->escape($entry->created) ?> <hr></TD>
    </TR>

    <?php endforeach ?>
</TABLE>